anchor_version = "0.29"

[features]
seeds = false

[programs.mainnet]
amm_v3 = "CLK8pJyTV17Mwq3MrgbbojEiVXcmrMYC3J59JC9xhgNQ"

# [programs.devnet]
# amm_v3 = "devi51mZmdwUJGU9hjN27vEz64Gps7uUefqxg27EAtH"

[registry]
url = "https://github.com/Solar-Studio/solar-clmm"

[provider]
cluster = "https://eclipse.helius-rpc.com"
wallet = "/Users/visheshsachdev/.config/solana/id.json"

# [[test.genesis]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
# program = "./external-programs/spl_token_metadata.so"